import {
  Customer,
  Appointment,
  Service,
  Staff,
  RecoveryEvent,
  MessageItem,
  NotificationItem,
  SalonProfile,
} from '@/types';

export const mockSalonProfile: SalonProfile = {
  name: 'Luxe Aura Salon & Spa',
  tagline: 'Premium Hair & Wellness Care',
  city: 'Bandra West, Mumbai',
  address: 'Plot 42, 14th Road, Near Khar Gymkhana, Bandra West, Mumbai 400050',
  phone: '+91 98201 54321',
  ownerName: 'Priyanshu Sharma',
  ownerEmail: 'priyanshu@luxeaura.in',
  category: 'Salon & Spa',
  currency: 'INR',
  language: 'English (India)',
  whatsappProvider: 'Gupshup',
  whatsappPhoneNumber: '+91 98201 54321',
  whatsappConnected: true,
  webhookStatus: 'healthy',
  reminderAdvanceHours: 24,
  noShowFollowupMinutes: 30,
  maxFollowupAttempts: 2,
  quietHoursStart: '21:30',
  quietHoursEnd: '09:30',
};

export const mockStaff: Staff[] = [
  {
    id: 'staff-1',
    name: 'Priya Nair',
    role: 'Creative Director & Master Stylist',
    initials: 'PN',
    color: '#0f766e',
    serviceIds: ['srv-1', 'srv-2', 'srv-5'],
    workingHours: {
      start: '10:00',
      end: '19:30',
      days: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    active: true,
    phone: '+91 98192 11001',
    appointmentsTodayCount: 5,
  },
  {
    id: 'staff-2',
    name: 'Rohan Deshmukh',
    role: 'Senior Hair Colorist',
    initials: 'RD',
    color: '#b45309',
    serviceIds: ['srv-1', 'srv-2', 'srv-5'],
    workingHours: {
      start: '10:30',
      end: '20:00',
      days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    },
    active: true,
    phone: '+91 98192 22002',
    appointmentsTodayCount: 4,
  },
  {
    id: 'staff-3',
    name: 'Meera Sen',
    role: 'Lead Esthetician & Skin Specialist',
    initials: 'MS',
    color: '#0284c7',
    serviceIds: ['srv-3', 'srv-6'],
    workingHours: {
      start: '10:00',
      end: '19:00',
      days: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat', 'Sun'],
    },
    active: true,
    phone: '+91 98192 33003',
    appointmentsTodayCount: 4,
  },
  {
    id: 'staff-4',
    name: 'Anjali Patel',
    role: 'Nail Artist & Spa Therapist',
    initials: 'AP',
    color: '#be185d',
    serviceIds: ['srv-4', 'srv-6'],
    workingHours: {
      start: '11:00',
      end: '20:00',
      days: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    active: true,
    phone: '+91 98192 44004',
    appointmentsTodayCount: 3,
  },
];

export const mockServices: Service[] = [
  {
    id: 'srv-1',
    name: 'Signature Haircut & Style',
    category: 'Hair',
    durationMinutes: 45,
    price: 850,
    typicalReturnDays: 30,
    active: true,
    staffIds: ['staff-1', 'staff-2'],
    reminderCopyTemplate: 'Hi {name}, your hair styling appointment with {staff} is confirmed for {time}. Reply 1 to Confirm or 2 to Reschedule.',
    bookingCount: 142,
  },
  {
    id: 'srv-2',
    name: 'Balayage & Global Hair Colour',
    category: 'Hair',
    durationMinutes: 150,
    price: 4200,
    typicalReturnDays: 45,
    active: true,
    staffIds: ['staff-1', 'staff-2'],
    reminderCopyTemplate: 'Hi {name}, your Balayage colour session with {staff} is on {date} at {time}. We have blocked 2.5 hours for you.',
    bookingCount: 88,
  },
  {
    id: 'srv-3',
    name: 'Hydra-Glow Radiance Facial',
    category: 'Face & Skin',
    durationMinutes: 60,
    price: 2400,
    typicalReturnDays: 30,
    active: true,
    staffIds: ['staff-3'],
    reminderCopyTemplate: 'Hi {name}, your Hydra-Glow Facial with {staff} is tomorrow at {time}. We look forward to seeing you!',
    bookingCount: 115,
  },
  {
    id: 'srv-4',
    name: 'Deluxe Gel Manicure & Pedicure',
    category: 'Hands & Feet',
    durationMinutes: 60,
    price: 1500,
    typicalReturnDays: 21,
    active: true,
    staffIds: ['staff-4'],
    reminderCopyTemplate: 'Hi {name}, ready for your Mani-Pedi refresh? Your slot with {staff} is at {time}.',
    bookingCount: 96,
  },
  {
    id: 'srv-5',
    name: 'Brazilian Keratin Smoothing',
    category: 'Treatments',
    durationMinutes: 180,
    price: 6500,
    typicalReturnDays: 90,
    active: true,
    staffIds: ['staff-1', 'staff-2'],
    reminderCopyTemplate: 'Hi {name}, your Keratin treatment with {staff} is confirmed for {date} at {time}.',
    bookingCount: 42,
  },
  {
    id: 'srv-6',
    name: 'Ayurvedic Aromatherapy Body Spa',
    category: 'Spa & Body',
    durationMinutes: 75,
    price: 3200,
    typicalReturnDays: 30,
    active: true,
    staffIds: ['staff-3', 'staff-4'],
    reminderCopyTemplate: 'Hi {name}, your relaxing Spa session with {staff} is scheduled for {time}.',
    bookingCount: 64,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Aisha Patel',
    phone: '+91 98201 12345',
    email: 'aisha.patel@gmail.com',
    initials: 'AP',
    tags: ['VIP', 'Colour Regular', 'Weekend Preferred'],
    lastVisit: '2026-08-05',
    nextDueDate: '2026-09-15',
    preferredService: 'Balayage & Global Hair Colour',
    preferredStaff: 'Priya Nair',
    typicalReturnDays: 40,
    totalVisits: 14,
    totalSpend: 48600,
    status: 'active',
    notes: 'Prefers ammonia-free L’Oreal Inoa 5.3 shades. Very punctual.',
    formulaNotes: 'Roots: 5.1 (20vol), Mid-ends: Balayage Blond Studio + Dialight 9.02',
    createdAt: '2025-03-10',
  },
  {
    id: 'cust-2',
    name: 'Riya Shah',
    phone: '+91 98202 23456',
    email: 'riya.shah@rediffmail.com',
    initials: 'RS',
    tags: ['Recovered', 'No-Show Risk'],
    lastVisit: '2026-07-14',
    nextDueDate: '2026-09-08',
    preferredService: 'Hydra-Glow Radiance Facial',
    preferredStaff: 'Meera Sen',
    typicalReturnDays: 30,
    totalVisits: 8,
    totalSpend: 19200,
    status: 'due_soon',
    notes: 'Reschedules frequently due to corporate travel. Sensitive skin on forehead.',
    createdAt: '2025-06-20',
  },
  {
    id: 'cust-3',
    name: 'Neha Mehta',
    phone: '+91 98203 34567',
    email: 'neha.mehta@outlook.com',
    initials: 'NM',
    tags: ['Recovered Lapsed', 'High Value'],
    lastVisit: '2026-06-18',
    nextDueDate: '2026-07-20',
    preferredService: 'Brazilian Keratin Smoothing',
    preferredStaff: 'Rohan Deshmukh',
    typicalReturnDays: 60,
    totalVisits: 6,
    totalSpend: 36000,
    status: 'overdue',
    notes: 'Returned after receiving the 52-day automated rebooking nudge.',
    createdAt: '2025-01-15',
  },
  {
    id: 'cust-4',
    name: 'Kavya Desai',
    phone: '+91 98204 45678',
    email: 'kavya.desai@gmail.com',
    initials: 'KD',
    tags: ['Nails Fanatic', 'Weekly'],
    lastVisit: '2026-08-28',
    nextDueDate: '2026-09-18',
    preferredService: 'Deluxe Gel Manicure & Pedicure',
    preferredStaff: 'Anjali Patel',
    typicalReturnDays: 21,
    totalVisits: 19,
    totalSpend: 28500,
    status: 'active',
    notes: 'Loves pastel French ombré. Likes iced black coffee during service.',
    createdAt: '2025-04-02',
  },
  {
    id: 'cust-5',
    name: 'Ananya Sharma',
    phone: '+91 98205 56789',
    email: 'ananya.s@techcorp.in',
    initials: 'AS',
    tags: ['Lapsed', 'Haircut Regular'],
    lastVisit: '2026-05-12',
    nextDueDate: '2026-06-12',
    preferredService: 'Signature Haircut & Style',
    preferredStaff: 'Priya Nair',
    typicalReturnDays: 30,
    totalVisits: 5,
    totalSpend: 4250,
    status: 'lapsed',
    notes: 'Overdue by 88 days. VertOps automated nudge queued for WhatsApp.',
    createdAt: '2025-08-11',
  },
  {
    id: 'cust-6',
    name: 'Pooja Verma',
    phone: '+91 98206 67890',
    email: 'pooja.verma@fashionhub.com',
    initials: 'PV',
    tags: ['VIP', 'Spa Regular'],
    lastVisit: '2026-08-10',
    nextDueDate: '2026-09-10',
    preferredService: 'Ayurvedic Aromatherapy Body Spa',
    preferredStaff: 'Meera Sen',
    typicalReturnDays: 30,
    totalVisits: 11,
    totalSpend: 35200,
    status: 'due_soon',
    notes: 'Prefers evening slots after 6:30 PM. Jasmine aroma oil preferred.',
    createdAt: '2025-02-18',
  },
  {
    id: 'cust-7',
    name: 'Sneha Reddy',
    phone: '+91 98207 78901',
    email: 'sneha.reddy@hyderabadmedia.in',
    initials: 'SR',
    tags: ['High Value'],
    lastVisit: '2026-07-22',
    nextDueDate: '2026-09-05',
    preferredService: 'Balayage & Global Hair Colour',
    preferredStaff: 'Rohan Deshmukh',
    typicalReturnDays: 45,
    totalVisits: 7,
    totalSpend: 29400,
    status: 'overdue',
    notes: 'Warm honey tones. Booking prompted via WhatsApp reminder.',
    createdAt: '2025-09-01',
  },
  {
    id: 'cust-8',
    name: 'Sunita Gupta',
    phone: '+91 98208 89012',
    email: 'sunita.gupta@gmail.com',
    initials: 'SG',
    tags: ['Skin Care'],
    lastVisit: '2026-08-15',
    nextDueDate: '2026-09-15',
    preferredService: 'Hydra-Glow Radiance Facial',
    preferredStaff: 'Meera Sen',
    typicalReturnDays: 30,
    totalVisits: 9,
    totalSpend: 21600,
    status: 'active',
    notes: 'Hydrating mask boost always added.',
    createdAt: '2025-05-14',
  },
  {
    id: 'cust-9',
    name: 'Megha Kulkarni',
    phone: '+91 98209 90123',
    email: 'megha.k@puneventure.com',
    initials: 'MK',
    tags: ['No-Show Recovered'],
    lastVisit: '2026-08-01',
    nextDueDate: '2026-09-01',
    preferredService: 'Signature Haircut & Style',
    preferredStaff: 'Priya Nair',
    typicalReturnDays: 30,
    totalVisits: 4,
    totalSpend: 3400,
    status: 'overdue',
    notes: 'Missed appointment on Aug 30, rescheduled via 1-click WhatsApp link.',
    createdAt: '2025-11-04',
  },
  {
    id: 'cust-10',
    name: 'Vikram Malhotra',
    phone: '+91 98210 01234',
    email: 'vikram.m@investorcap.in',
    initials: 'VM',
    tags: ['Men Grooming', 'Regular'],
    lastVisit: '2026-08-20',
    nextDueDate: '2026-09-10',
    preferredService: 'Signature Haircut & Style',
    preferredStaff: 'Priya Nair',
    typicalReturnDays: 20,
    totalVisits: 16,
    totalSpend: 13600,
    status: 'due_soon',
    notes: 'Classic textured fade + beard shapeup.',
    createdAt: '2025-03-22',
  },
];

// Today's appointments (Simulated for today's date)
export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    customerId: 'cust-1',
    customerName: 'Aisha Patel',
    customerPhone: '+91 98201 12345',
    serviceId: 'srv-2',
    serviceName: 'Balayage & Global Hair Colour',
    staffId: 'staff-1',
    staffName: 'Priya Nair',
    staffInitials: 'PN',
    startTime: '2026-09-09T10:30:00',
    endTime: '2026-09-09T13:00:00',
    durationMinutes: 150,
    status: 'confirmed',
    price: 4200,
    whatsappStatus: 'read',
    notes: 'Confirmed via WhatsApp at 9:15 AM today.',
  },
  {
    id: 'apt-2',
    customerId: 'cust-4',
    customerName: 'Kavya Desai',
    customerPhone: '+91 98204 45678',
    serviceId: 'srv-4',
    serviceName: 'Deluxe Gel Manicure & Pedicure',
    staffId: 'staff-4',
    staffName: 'Anjali Patel',
    staffInitials: 'AP',
    startTime: '2026-09-09T11:00:00',
    endTime: '2026-09-09T12:00:00',
    durationMinutes: 60,
    status: 'checked_in',
    price: 1500,
    whatsappStatus: 'replied',
    notes: 'Customer arrived on time, seated at nail station 2.',
  },
  {
    id: 'apt-3',
    customerId: 'cust-2',
    customerName: 'Riya Shah',
    customerPhone: '+91 98202 23456',
    serviceId: 'srv-3',
    serviceName: 'Hydra-Glow Radiance Facial',
    staffId: 'staff-3',
    staffName: 'Meera Sen',
    staffInitials: 'MS',
    startTime: '2026-09-09T12:00:00',
    endTime: '2026-09-09T13:00:00',
    durationMinutes: 60,
    status: 'confirmed',
    price: 2400,
    whatsappStatus: 'delivered',
    notes: 'WhatsApp reminder sent yesterday at 6:00 PM.',
  },
  {
    id: 'apt-4',
    customerId: 'cust-10',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98210 01234',
    serviceId: 'srv-1',
    serviceName: 'Signature Haircut & Style',
    staffId: 'staff-1',
    staffName: 'Priya Nair',
    staffInitials: 'PN',
    startTime: '2026-09-09T14:00:00',
    endTime: '2026-09-09T14:45:00',
    durationMinutes: 45,
    status: 'reminder_sent',
    price: 850,
    whatsappStatus: 'delivered',
  },
  {
    id: 'apt-5',
    customerId: 'cust-6',
    customerName: 'Pooja Verma',
    customerPhone: '+91 98206 67890',
    serviceId: 'srv-6',
    serviceName: 'Ayurvedic Aromatherapy Body Spa',
    staffId: 'staff-3',
    staffName: 'Meera Sen',
    staffInitials: 'MS',
    startTime: '2026-09-09T15:00:00',
    endTime: '2026-09-09T16:15:00',
    durationMinutes: 75,
    status: 'confirmed',
    price: 3200,
    whatsappStatus: 'read',
  },
  {
    id: 'apt-6',
    customerId: 'cust-9',
    customerName: 'Megha Kulkarni',
    customerPhone: '+91 98209 90123',
    serviceId: 'srv-1',
    serviceName: 'Signature Haircut & Style',
    staffId: 'staff-2',
    staffName: 'Rohan Deshmukh',
    staffInitials: 'RD',
    startTime: '2026-09-09T16:00:00',
    endTime: '2026-09-09T16:45:00',
    durationMinutes: 45,
    status: 'confirmed',
    price: 850,
    whatsappStatus: 'replied',
    isRecovered: true,
    recoveryEventId: 'rec-2',
    notes: 'Recovered no-show from last week via automated reschedule link.',
  },
  {
    id: 'apt-7',
    customerId: 'cust-3',
    customerName: 'Neha Mehta',
    customerPhone: '+91 98203 34567',
    serviceId: 'srv-5',
    serviceName: 'Brazilian Keratin Smoothing',
    staffId: 'staff-2',
    staffName: 'Rohan Deshmukh',
    staffInitials: 'RD',
    startTime: '2026-09-09T17:00:00',
    endTime: '2026-09-09T20:00:00',
    durationMinutes: 180,
    status: 'confirmed',
    price: 6500,
    whatsappStatus: 'read',
    isRecovered: true,
    recoveryEventId: 'rec-1',
    notes: 'Recovered lapsed customer (returned after 52 days).',
  },
  {
    id: 'apt-8',
    customerId: 'cust-8',
    customerName: 'Sunita Gupta',
    customerPhone: '+91 98208 89012',
    serviceId: 'srv-3',
    serviceName: 'Hydra-Glow Radiance Facial',
    staffId: 'staff-3',
    staffName: 'Meera Sen',
    staffInitials: 'MS',
    startTime: '2026-09-09T17:30:00',
    endTime: '2026-09-09T18:30:00',
    durationMinutes: 60,
    status: 'reminder_pending',
    price: 2400,
    whatsappStatus: 'scheduled',
  },
];

export const mockRecoveryEvents: RecoveryEvent[] = [
  {
    id: 'rec-1',
    customerId: 'cust-3',
    customerName: 'Neha Mehta',
    customerPhone: '+91 98203 34567',
    source: 'lapsed_customer',
    messageSentAt: '2026-09-06T11:20:00',
    responseAt: '2026-09-06T12:05:00',
    appointmentId: 'apt-7',
    serviceName: 'Brazilian Keratin Smoothing',
    serviceId: 'srv-5',
    estimatedRevenue: 6500,
    actualRevenue: 6500,
    status: 'appointment_booked',
    isActual: true,
    messagePreview: 'Hi Neha! It has been 52 days since your last hair care session with Rohan. Would you like to book your Keratin touchup this week?',
    replyPreview: 'Yes please! Rohan has a slot on Wednesday evening?',
    daysLapsed: 52,
  },
  {
    id: 'rec-2',
    customerId: 'cust-9',
    customerName: 'Megha Kulkarni',
    customerPhone: '+91 98209 90123',
    source: 'no_show',
    messageSentAt: '2026-09-01T15:30:00',
    responseAt: '2026-09-01T15:42:00',
    appointmentId: 'apt-6',
    serviceName: 'Signature Haircut & Style',
    serviceId: 'srv-1',
    estimatedRevenue: 850,
    actualRevenue: 850,
    status: 'appointment_booked',
    isActual: true,
    messagePreview: 'Hi Megha, we missed you today for your styling session. Would you like to reschedule for tomorrow or this weekend?',
    replyPreview: 'So sorry, got stuck in traffic! Let us do Wednesday 4 PM.',
    daysLapsed: 1,
  },
  {
    id: 'rec-3',
    customerId: 'cust-7',
    customerName: 'Sneha Reddy',
    customerPhone: '+91 98207 78901',
    source: 'due_nudge',
    messageSentAt: '2026-09-04T10:00:00',
    responseAt: '2026-09-04T11:15:00',
    serviceName: 'Balayage & Global Hair Colour',
    serviceId: 'srv-2',
    estimatedRevenue: 4200,
    status: 'replied',
    isActual: false,
    messagePreview: 'Hi Sneha, it’s been 44 days since your Balayage with Rohan. Time for your gloss & gloss refresh?',
    replyPreview: 'Hey, yes! Can we look at Saturday slots after 2 PM?',
    daysLapsed: 44,
  },
  {
    id: 'rec-4',
    customerId: 'cust-2',
    customerName: 'Riya Shah',
    customerPhone: '+91 98202 23456',
    source: 'no_show',
    messageSentAt: '2026-08-25T18:30:00',
    responseAt: '2026-08-25T19:00:00',
    appointmentId: 'apt-3',
    serviceName: 'Hydra-Glow Radiance Facial',
    serviceId: 'srv-3',
    estimatedRevenue: 2400,
    actualRevenue: 2400,
    status: 'visit_completed',
    isActual: true,
    messagePreview: 'Hi Riya, we noticed you could not make it today. Click here to pick a new time with Meera.',
    replyPreview: 'Rescheduled for Sept 9 at 12 PM. Thanks!',
    daysLapsed: 0,
  },
  {
    id: 'rec-5',
    customerId: 'cust-5',
    customerName: 'Ananya Sharma',
    customerPhone: '+91 98205 56789',
    source: 'lapsed_customer',
    messageSentAt: '2026-09-08T14:15:00',
    serviceName: 'Signature Haircut & Style',
    serviceId: 'srv-1',
    estimatedRevenue: 850,
    status: 'message_sent',
    isActual: false,
    messagePreview: 'Hi Ananya, Priya misses you at Luxe Aura! You are due for your haircut refresh. Book your slot today.',
    daysLapsed: 88,
  },
];

export const mockMessages: MessageItem[] = [
  {
    id: 'msg-1',
    customerId: 'cust-7',
    customerName: 'Sneha Reddy',
    customerPhone: '+91 98207 78901',
    customerInitials: 'SR',
    type: 'due_nudge',
    body: 'Hey, yes! Can we look at Saturday slots after 2 PM?',
    sentAt: '2026-09-04T11:15:00',
    deliveryStatus: 'replied',
    replyStatus: 'replied',
    needsReview: true,
    aiExtractedIntent: {
      intent: 'reschedule',
      extractedDate: 'Saturday, 12 Sept',
      extractedTime: 'After 2:00 PM',
      extractedService: 'Balayage & Global Hair Colour',
      confidence: 0.94,
      summary: 'Customer wants to book Balayage for Saturday post 2:00 PM with Rohan.',
    },
    suggestedReplies: [
      'We have Saturday 2:30 PM open with Rohan. Shall I book that for you?',
      'Saturday 4:00 PM is available. Would that suit your schedule?',
      'Let me share Rohan’s full schedule for this Saturday.',
    ],
    conversationHistory: [
      {
        id: 'c-1',
        sender: 'system',
        text: 'Hi Sneha, it’s been 44 days since your Balayage with Rohan. Time for your gloss & root refresh? ✨ Reply to pick a slot.',
        timestamp: '2026-09-04T10:00:00',
        status: 'read',
      },
      {
        id: 'c-2',
        sender: 'customer',
        text: 'Hey, yes! Can we look at Saturday slots after 2 PM?',
        timestamp: '2026-09-04T11:15:00',
      },
    ],
  },
  {
    id: 'msg-2',
    customerId: 'cust-1',
    customerName: 'Aisha Patel',
    customerPhone: '+91 98201 12345',
    customerInitials: 'AP',
    type: 'appointment_reminder',
    body: 'Confirmed! See you at 10:30 AM.',
    sentAt: '2026-09-09T09:15:00',
    deliveryStatus: 'read',
    replyStatus: 'replied',
    needsReview: false,
    aiExtractedIntent: {
      intent: 'confirm',
      confidence: 0.99,
      summary: 'Customer confirmed 10:30 AM appointment.',
    },
    suggestedReplies: ['Thank you Aisha, Priya is ready for you!'],
    conversationHistory: [
      {
        id: 'c-3',
        sender: 'system',
        text: 'Hi Aisha, gentle reminder for your Balayage appointment today at 10:30 AM with Priya Nair at Luxe Aura. Reply 1 to Confirm.',
        timestamp: '2026-09-09T08:00:00',
        status: 'read',
      },
      {
        id: 'c-4',
        sender: 'customer',
        text: 'Confirmed! See you at 10:30 AM.',
        timestamp: '2026-09-09T09:15:00',
      },
    ],
  },
  {
    id: 'msg-3',
    customerId: 'cust-9',
    customerName: 'Megha Kulkarni',
    customerPhone: '+91 98209 90123',
    customerInitials: 'MK',
    type: 'no_show_recovery',
    body: 'So sorry, got stuck in traffic! Let us do Wednesday 4 PM.',
    sentAt: '2026-09-01T15:42:00',
    deliveryStatus: 'replied',
    replyStatus: 'replied',
    needsReview: false,
    aiExtractedIntent: {
      intent: 'reschedule',
      extractedDate: 'Wednesday, 9 Sept',
      extractedTime: '4:00 PM',
      extractedService: 'Signature Haircut & Style',
      confidence: 0.96,
      summary: 'Customer rescheduled missed visit to Wed 4:00 PM with Rohan.',
    },
    suggestedReplies: ['You are all set for Wednesday at 4:00 PM with Rohan!'],
    conversationHistory: [
      {
        id: 'c-5',
        sender: 'system',
        text: 'Hi Megha, we missed you for your haircut at 3:00 PM today. No worries! Reply with your preferred day to reschedule.',
        timestamp: '2026-09-01T15:30:00',
        status: 'read',
      },
      {
        id: 'c-6',
        sender: 'customer',
        text: 'So sorry, got stuck in traffic! Let us do Wednesday 4 PM.',
        timestamp: '2026-09-01T15:42:00',
      },
      {
        id: 'c-7',
        sender: 'salon',
        text: 'Booked! You are scheduled with Rohan Deshmukh on Wed, Sep 9 at 4:00 PM.',
        timestamp: '2026-09-01T15:45:00',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'msg-4',
    customerId: 'cust-5',
    customerName: 'Ananya Sharma',
    customerPhone: '+91 98205 56789',
    customerInitials: 'AS',
    type: 'due_nudge',
    body: 'Hi Ananya, Priya misses you at Luxe Aura! You are due for your haircut refresh. Book your slot today.',
    sentAt: '2026-09-08T14:15:00',
    deliveryStatus: 'delivered',
    replyStatus: 'pending',
    needsReview: false,
    conversationHistory: [
      {
        id: 'c-8',
        sender: 'system',
        text: 'Hi Ananya, Priya misses you at Luxe Aura! It has been 88 days since your last haircut. Click here to pick a time: https://luxeaura.in/b/as88',
        timestamp: '2026-09-08T14:15:00',
        status: 'delivered',
      },
    ],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    iconType: 'recovery',
    title: '₹38,500 Recovered This Month',
    description: '47 lapsed customers rebooked and 12 no-shows were successfully recovered.',
    timestamp: '2026-09-09T09:00:00',
    read: false,
    actionLabel: 'View Recovery Report',
    actionUrl: '/recovery',
  },
  {
    id: 'notif-2',
    iconType: 'whatsapp',
    title: 'Customer reply needs review',
    description: 'Sneha Reddy requested a Saturday slot after 2:00 PM for Balayage.',
    timestamp: '2026-09-04T11:15:00',
    read: false,
    actionLabel: 'Review & Confirm',
    actionUrl: '/messages/msg-1',
    relatedId: 'msg-1',
  },
  {
    id: 'notif-3',
    iconType: 'appointment',
    title: 'Aisha Patel confirmed appointment',
    description: 'Appointment confirmed for Balayage at 10:30 AM today with Priya Nair.',
    timestamp: '2026-09-09T09:15:00',
    read: true,
    actionLabel: 'View Calendar',
    actionUrl: '/calendar',
  },
  {
    id: 'notif-4',
    iconType: 'recovery',
    title: 'No-show recovered via WhatsApp',
    description: 'Megha Kulkarni rescheduled her missed haircut to today at 4:00 PM.',
    timestamp: '2026-09-01T15:45:00',
    read: true,
    actionLabel: 'View Appointment',
    actionUrl: '/calendar',
  },
  {
    id: 'notif-5',
    iconType: 'whatsapp',
    title: 'WhatsApp Provider Healthy',
    description: 'Gupshup webhook latency 140ms. Delivery rate 99.4%.',
    timestamp: '2026-09-08T08:00:00',
    read: true,
    actionLabel: 'WhatsApp Settings',
    actionUrl: '/settings/whatsapp',
  },
];

// Recovery overview KPIs
export const mockRecoveryMetrics = {
  estimatedRevenueRecovered: 38500,
  customersRecovered: 47,
  noShowsThisMonth: 31,
  noShowsRescheduled: 12,
  rebookingRate: 64, // 64%
  todayAppointmentsCount: 18,
  avgRecoveryValue: 820,
  previousPeriodRevenue: 29400,
  growthPercentage: 30.9,
  funnelData: [
    { stage: 'Customers Due', count: 184, dropoff: '100%' },
    { stage: 'WhatsApp Sent', count: 172, dropoff: '93.5%' },
    { stage: 'Responded', count: 118, dropoff: '64.1%' },
    { stage: 'Booked Visit', count: 68, dropoff: '37.0%' },
    { stage: 'Visit Completed', count: 59, dropoff: '32.1%' },
  ],
  revenueTrend: [
    { date: '01 Sep', appointments: 14, recoveredBookings: 3, recoveredRevenue: 2450 },
    { date: '02 Sep', appointments: 16, recoveredBookings: 4, recoveredRevenue: 3800 },
    { date: '03 Sep', appointments: 19, recoveredBookings: 5, recoveredRevenue: 4900 },
    { date: '04 Sep', appointments: 15, recoveredBookings: 4, recoveredRevenue: 3200 },
    { date: '05 Sep', appointments: 22, recoveredBookings: 7, recoveredRevenue: 6800 },
    { date: '06 Sep', appointments: 25, recoveredBookings: 9, recoveredRevenue: 8100 },
    { date: '07 Sep', appointments: 20, recoveredBookings: 6, recoveredRevenue: 4750 },
    { date: '08 Sep', appointments: 17, recoveredBookings: 4, recoveredRevenue: 2900 },
    { date: '09 Sep', appointments: 18, recoveredBookings: 5, recoveredRevenue: 4200 },
  ],
};
