from app.schemas.common import BaseSchema, PaginationParams, PaginatedResponse, ResponseEnvelope
from app.schemas.auth import (
    OTPRequest,
    OTPVerifyRequest,
    PasswordLoginRequest,
    RegisterRequest,
    RefreshTokenRequest,
    UserResponse,
    TokenResponse,
    SalonMembershipInfo,
)
from app.schemas.salon import (
    BusinessHoursCreate,
    BusinessHoursResponse,
    SalonCreate,
    SalonUpdate,
    SalonResponse,
)
from app.schemas.staff import (
    StaffWorkingHoursSchema,
    StaffCreate,
    StaffUpdate,
    StaffResponse,
)
from app.schemas.service import (
    ServiceCategoryCreate,
    ServiceCategoryResponse,
    ServiceCreate,
    ServiceUpdate,
    ServiceResponse,
)
from app.schemas.customer import (
    CustomerPreferenceSchema,
    CustomerCreate,
    CustomerUpdate,
    CustomerResponse,
    CustomerDetailResponse,
    CustomerImportItem,
    CustomerImportBatchRequest,
    CustomerImportResponse,
)
from app.schemas.appointment import (
    AppointmentItemInput,
    AppointmentCreate,
    AppointmentUpdate,
    AppointmentStatusChange,
    AppointmentServiceResponse,
    AppointmentResponse,
    AppointmentDetailResponse,
)
from app.schemas.calendar import (
    TimeSlot,
    StaffCalendarDay,
    CalendarQuery,
    CalendarViewResponse,
)
from app.schemas.recovery import (
    RecoveryEventResponse,
    RecoveryMetricsResponse,
    ManualRecoveryTriggerRequest,
)
from app.schemas.message import (
    SendMessageRequest,
    MessageResponse,
    ThreadResponse,
    ThreadDetailResponse,
    WhatsAppWebhookPayload,
)
from app.schemas.automation import (
    AutomationRuleCreate,
    AutomationRuleUpdate,
    AutomationRuleResponse,
    AutomationRunResponse,
    TriggerAutomationRunRequest,
)
from app.schemas.dashboard import (
    ActivityFeedItem,
    RevenueRecoveryCard,
    TodayOverview,
    ChartDataPoint,
    DashboardSummaryResponse,
)
from app.schemas.ai import (
    AIParseRequest,
    ExtractedBookingEntities,
    AIParseResponse,
    AIDraftReplyRequest,
    AIDraftReplyResponse,
)
from app.schemas.settings import (
    WhatsAppSettingsUpdate,
    WhatsAppAccountResponse,
    SalonSettingsUpdate,
)

__all__ = [
    "BaseSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ResponseEnvelope",
    "OTPRequest",
    "OTPVerifyRequest",
    "PasswordLoginRequest",
    "RegisterRequest",
    "RefreshTokenRequest",
    "UserResponse",
    "TokenResponse",
    "SalonMembershipInfo",
    "BusinessHoursCreate",
    "BusinessHoursResponse",
    "SalonCreate",
    "SalonUpdate",
    "SalonResponse",
    "StaffWorkingHoursSchema",
    "StaffCreate",
    "StaffUpdate",
    "StaffResponse",
    "ServiceCategoryCreate",
    "ServiceCategoryResponse",
    "ServiceCreate",
    "ServiceUpdate",
    "ServiceResponse",
    "CustomerPreferenceSchema",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerResponse",
    "CustomerDetailResponse",
    "CustomerImportItem",
    "CustomerImportBatchRequest",
    "CustomerImportResponse",
    "AppointmentItemInput",
    "AppointmentCreate",
    "AppointmentUpdate",
    "AppointmentStatusChange",
    "AppointmentServiceResponse",
    "AppointmentResponse",
    "AppointmentDetailResponse",
    "TimeSlot",
    "StaffCalendarDay",
    "CalendarQuery",
    "CalendarViewResponse",
    "RecoveryEventResponse",
    "RecoveryMetricsResponse",
    "ManualRecoveryTriggerRequest",
    "SendMessageRequest",
    "MessageResponse",
    "ThreadResponse",
    "ThreadDetailResponse",
    "WhatsAppWebhookPayload",
    "AutomationRuleCreate",
    "AutomationRuleUpdate",
    "AutomationRuleResponse",
    "AutomationRunResponse",
    "TriggerAutomationRunRequest",
    "ActivityFeedItem",
    "RevenueRecoveryCard",
    "TodayOverview",
    "ChartDataPoint",
    "DashboardSummaryResponse",
    "AIParseRequest",
    "ExtractedBookingEntities",
    "AIParseResponse",
    "AIDraftReplyRequest",
    "AIDraftReplyResponse",
    "WhatsAppSettingsUpdate",
    "WhatsAppAccountResponse",
    "SalonSettingsUpdate",
]
